apiVersion: v1
kind: Service
metadata:
  name: salary-mlops-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: salary-mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500